### ISSUE TITLE
Incorrect shapes for faint constellations

### ISSUE THREAD

**Issue by pupnewfster** [Swordstone86/AstrologicalSorcery#2] opened 2020-12-21 15:13 UTC
Mainly opening this just in case it is a bug and not intended, but using astrological sorcery 1.16.4-1.3.0, the pattern for OPHIUCHUS is different than in the picture on the curseforge page. The pattern I am seeing is: 
![image](https://user-images.githubusercontent.com/1203288/102791291-cb3d6d80-4374-11eb-92ce-806cc594e3a5.png)
I also see that on the constellation paper it and all the other faint constellations are using different ones than on the pictures in curseforge (CORONA BOREALIS is even using the same one as CAPRICORNUS), though the only one I have found in the night sky so far is OPHIUCHUS.

**Comment by Swordstone86** [comment] 2020-12-21 15:37
Thank you for this report, this is definitely unintended and most likely
related to how faint constellations were slightly reworked from 1.12. Will
work on a fix now.

**Comment by Swordstone86** [comment] 2020-12-23 01:51
@pupnewfster I'm unable to reproduce this issue locally. Can you give me a little more information so I can try to reproduce this?

1. The version of Astral Sorcery you're using
2. Your Forge version

If you have a log from your client, that will work great.

For reference, here's what I see on my end:
![image](https://user-images.githubusercontent.com/2717030/102949958-878f5480-4497-11eb-9c25-7e95b16ea9cc.png)

**Comment by pupnewfster** [comment] 2020-12-23 02:38
Maybe it has something to do with being on a server?
Astral sorcery version: 1.16.4-1.13.8
Forge version: 1.16.4 - 35.1.13

[server latest.log](https://github.com/Swordstone86/AstrologicalSorcery/files/5732966/server.latest.log)
[client latest.log](https://github.com/Swordstone86/AstrologicalSorcery/files/5732967/client.latest.log)

**Comment by Swordstone86** [comment] 2020-12-23 04:13
Looks like it was a regression caused by Astral Sorcery 1.16.4-1.13.8 (I believe HellfirePvP/AstralSorcery@f558b7b, but I'm not sure) that unintentionally broke how I modify constellations. 

Fixed by 15a41e8aba2a9e34bf918d583b19000a01b30706, with some more robust code that should hopefully prevent this from happening again. Thanks for the report!

**Closed as completed by Swordstone86** 2020-12-23 04:13 UTC
Labels: bug
