### ISSUE TITLE
Missing Moon Phases

### ISSUE THREAD

**Issue by CodexArchive** [Swordstone86/AstrologicalSorcery#3] opened 2021-03-11 13:55 UTC
I've noticed that the moon phases at the bottom of the page for Scorpius and Cancer are both currently replaced with astralsorcery.journal.constellation.unknown. Will these be fixed in a future update?

**Comment by Swordstone86** [comment] 2021-03-13 18:58
Issue was caused by an outdated lang file. Fixed in c21fca5.

**Closed as completed** 2021-03-13 18:58 UTC
Labels: bug
